/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./src/**/*.{js,jsx,ts,tsx}"],
  theme: {
    extend: {
      fontFamily: {
        sans: [
          "Hanken Grotesk, -apple-system",
          "Segoe UI",
          "Helvetica",
          "sans-serif",
        ],
      },
      fontSize: {
        small: ["0.8rem", "1.1rem"],
        medium: ["1.15rem", "1.5rem"],
      },
      colors: {
        primary: "#695EFF",
        secondary: "#182737",
        darkBg: "#0A1A2B",
        lightBg: "#EFEFF8",
        lightGrey: "#D1D1E3",
        dark2: "#575D63",
        lightBlue: "#EDF1F4",
        facebook: "#506ECC",
        greyBg: "#EDF1F4",
        grey0: "#F6F8F9",
        grey1: "#E6EAED",
        grey2: "#9A9A9A",
        grey3: "#3e3e3e",
        textGrey: "#777777",
        borderGrey: "#D6D8DA",
        borderLightGrey: "#ECEFF1",
      },
      boxShadow: {
        container: "1px 15px 50px 0px rgba(216, 222, 232, 0.6)",
        hover: "0px 0px 25px 0px rgba(0, 0, 0, 0.1)",
        cloud: "0px 3px 6px 0px rgba(0, 0, 0, 0.16)",
      },
      borderRadius: {
        base: "3px",
      },
      maxWidth: {
        small: "22rem",
      },
    },
  },
  plugins: [],
  safelist: [
    "text-white",
    "text-medium",
    "text-base",
    "text-small",
    "bg-primary",
    "border-primary",
    "bg-transparent",
    "border-transparent",
    "py-5",
    "py-2",
    "py-3",
    "px-5",
    "px-2",
    "py-3",
    "py-4",
    "sm:p-10",
    "p-10",
    "px-16",
    "w-full",
    "md:my-14",
    "max-w-sm",
    "max-w-small",
    "cursor-not-allowed",
    "pointer-events-none",
    "max-h-none",
    "overflow-visible",
    "fill-white",
  ],
};
